/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppPost: typeof import('./src/components/AppPost.vue')['default']
    AppSlide: typeof import('./src/components/AppSlide.vue')['default']
    AppTab: typeof import('./src/components/AppTab.vue')['default']
    AppVideos: typeof import('./src/components/AppVideos.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sample: typeof import('./src/components/sample.vue')['default']
    SocialInfo: typeof import('./src/components/SocialInfo.vue')['default']
  }
}
